### PR TITLE
Adds XO linting. Closes #18

### LINKED ISSUE #18: add linter to development dependencies
In my latest PR #17, I cleaned up a lot of code inconsistencies (mostly just spaces and tabs), to make things a bit more uniform, but I propose that a linter be added to the `devDependencies`, so that developers working on new features or pull requests can all adhere to the same coding style. 

The best tool I have seen for this is [XO](https://github.com/sindresorhus/xo), which is super simple to use. Just install it with:

`npm install --save-dev xo`

and then add this to your `package.json`: 

```
"scripts": {
  "test": "xo"
}
```

That's all you need to get linting support, but you can take it a step further and get Travis to run your linting on all Pull Requests that get submitted (highly recommended) by adding a `.travis.yml` file with:

```
language: node_js
node_js:
  - 'stable'
```

and then whenever a new pull request (from any user) has been submitted, Travis will run the linting, and will report that the PR is not ready to be merged until the linting issues have been fixed. 

**Its a beautiful thing!** :smile:

### PR DESCRIPTION
**Pull request by radiovisual**
For a full breakdown of everything that got "linted" in this PR:

<pre>
/Users/michael/forks/linear/main.js
   17:5   error  'rulers' is never reassigned, use 'const' instead            prefer-const
   29:6   error  '_windowInfo' is never reassigned, use 'const' instead       prefer-const
   98:5   error  'toggleRuler' is never reassigned, use 'const' instead       prefer-const
   98:19  error  Unexpected parentheses around single function argument       babel/arrow-parens
   99:21  error  Unexpected parentheses around single function argument       babel/arrow-parens
  123:17  error  Unexpected function expression                               prefer-arrow-callback
  124:6   error  'trayIcon' is never reassigned, use 'const' instead          prefer-const
  126:2   error  Unexpected var, use let or const instead                     no-var
  181:6   error  'trayMenu' is never reassigned, use 'const' instead          prefer-const
  182:6   error  'toggleRulersMenu' is never reassigned, use 'const' instead  prefer-const
  186:6   error  'appMenu' is never reassigned, use 'const' instead           prefer-const
  232:17  error  Unexpected parentheses around single function argument       babel/arrow-parens

/Users/michael/forks/linear/src/app/ruler/ruler.js
   10:5   error  'borders' is never reassigned, use 'const' instead         prefer-const
   17:5   error  'info' is never reassigned, use 'const' instead            prefer-const
   22:5   error  'centerGuides' is never reassigned, use 'const' instead    prefer-const
   35:5   error  'unitStrategies' is never reassigned, use 'const' instead  prefer-const
   61:6   error  'unit' is never reassigned, use 'const' instead            prefer-const
   76:5   error  'contextMenu' is never reassigned, use 'const' instead     prefer-const
   83:7   error  'bounds' is never reassigned, use 'const' instead          prefer-const
   84:7   error  'position' is never reassigned, use 'const' instead        prefer-const
   95:36  error  Unexpected function expression                             prefer-arrow-callback
   96:6   error  'shift' is never reassigned, use 'const' instead           prefer-const
  107:34  error  Unexpected function expression                             prefer-arrow-callback
  109:2   error  Split 'let' declarations into multiple statements          one-var
  109:6   error  'up' is never reassigned, use 'const' instead              prefer-const
  110:3   error  'down' is never reassigned, use 'const' instead            prefer-const
  111:3   error  'left' is never reassigned, use 'const' instead            prefer-const
  112:3   error  'right' is never reassigned, use 'const' instead           prefer-const
  113:3   error  'shift' is never reassigned, use 'const' instead           prefer-const
  116:6   error  'position' is never reassigned, use 'const' instead        prefer-const
  117:6   error  'x' is never reassigned, use 'const' instead               prefer-const
  118:6   error  'y' is never reassigned, use 'const' instead               prefer-const
  121:6   error  'increment' is never reassigned, use 'const' instead       prefer-const
  143:40  error  Unexpected function expression                             prefer-arrow-callback

/Users/michael/forks/linear/src/app/settings/settings.js
  17:5   error  'settingsChangedDecorator' is never reassigned, use 'const' instead  prefer-const
  17:32  error  Unexpected parentheses around single function argument               babel/arrow-parens
  17:40  error  Unexpected parentheses around single function argument               babel/arrow-parens
  26:6   error  'unit' is never reassigned, use 'const' instead                      prefer-const
  27:6   error  'size' is never reassigned, use 'const' instead                      prefer-const
  33:22  error  Unexpected parentheses around single function argument               babel/arrow-parens
  34:68  error  Unexpected parentheses around single function argument               babel/arrow-parens
  39:64  error  Unexpected parentheses around single function argument               babel/arrow-parens
</pre>

### CODE REVIEW

**Comment by radiovisual** [comment]
After this gets merged, if you have travis hooked up to the repo, then all future pull requests will be linted before merge. A beautiful thing!

**Comment by mikaa123** [comment]
A beautiful thing indeed! Awesome :+1:

**Comment by mikaa123** [comment]
Travis is hooked! Thanks again!

**Comment by radiovisual** [comment]
Awesome! No problem!

**Pull request merged**
